nelmio_cors:
  defaults:
    origin_regex: false
    allow_origin: [ '*' ]
#    allow_origin: [ '^https?://(pg)/?$' ]
#    allow_origin: [ 'http://profguide.io', 'http://pg' ]
    allow_methods: [ 'GET', 'POST' ]
    allow_headers: [ '*' ]
    expose_headers: [ '*' ]
    max_age: 3600
  paths:
    '^/':
      origin_regex: true
      allow_methods: [ 'POST', 'PUT', 'GET' ]