vich_uploader:
  db_driver: orm

  metadata:
    type: attribute

  mappings:
    articles:
      uri_prefix: /images/articles
      upload_destination: '%kernel.project_dir%/public/images/articles'
      namer:
        service: Vich\UploaderBundle\Naming\HashNamer
        options: { algorithm: 'sha256', length: 12 }
      inject_on_load: false
      delete_on_update: true
      delete_on_remove: true