vich_uploader:
    db_driver: orm

    mappings:
        thumbnails:
            uri_prefix: /images/thumbnails
            upload_destination: '%kernel.project_dir%/public/images/thumbnails'
            namer:
              service: Vich\UploaderBundle\Naming\HashNamer
              options: { algorithm: 'sha256', length: 10 }
