name: tn

services:
  nginx:
    image: nginx:alpine
    working_dir: /app
    volumes:
      - ./:/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8030:80"
    networks:
      - tn-network

  database:
    image: mariadb
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tn
    volumes:
      - database_data:/var/lib/mysql
      - ./docker/dumps:/dumps
    working_dir: /dumps
    networks:
      - tn-network

  php-fpm:
    build:
      context: docker/php-fpm
      dockerfile: Dockerfile
    depends_on:
      - database
    volumes:
      - ./:/app
      - ./var:/app/var
    working_dir: /app
    user: 1000:1000
    networks:
      - tn-network

networks:
  tn-network:

volumes:
  ###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
