#!/bin/bash
if [[ "cache" == $1 ]]; then
  sudo chown -R wolfandman:wolfandman var
  echo "php bin/console cache:clear"
  #  php bin/console cache:clear
  rm var/cache/ -r
  echo "sudo chown -R www-data:www-data var"
  sudo chown -R www-data:www-data var
  echo "done"
fi
if [[ "env" == $1 ]]; then
  symfony composer dump-env prod
fi