controllers:
  resource: ../../src/Controller/
  type: annotation
  prefix:
    ru: '' # don't prefix URLs for Russian, the default locale
    en: '/en'
#  defaults:
#    _locale: '%app.default_locale%'
#    prefix: /{_locale}
#    requirements:
#      _locale: '%app.supported_locales%'

kernel:
  resource: ../../src/Kernel.php
  type: annotation
